#include <iostream>

// Reference => https://www.youtube.com/watch?v=8jLOx1hD3_o
// (freeCodeCamp.org)

const double Pi {3.1415926535897932384626433832795};

class Cylinder{
    public :
        // Constructors
        /*Cylinder(){   
            // If you don't have any constructor in your class, compiler will generate an empty one.
            // called as default constructor generated by the compiler
        }*/

        Cylinder(){ // Constructors used by the compiler to built your objects
            base_radius = 2.0;
            height = 2.0;
        }

        Cylinder(double base_param, double height_param){
            base_radius = base_param;
            height = height_param;
        }

        // Functions(methods)
        double volume(){
            return Pi * base_radius * base_radius * height;
        }

    private :
        // Member variables
        double base_radius {1};
        double height {1};
};

int main(){

    Cylinder cylinder1(10,4); // Object
    //Cylinder cylinder1;
                        // if you left empty cylinder1 and without paranthesis, it will choose the first constructor.
                        // but if you enter parameters, it will choose the second constructor.

    std::cout << "volume of cylinder : " << cylinder1.volume() << std::endl;
    
    return 0;
}